#!/bin/bash
node_modules/.bin/browserify --debug \
    -r jquery \
    -r underscore \
    -r backbone \
    -r react/addons \
    -r superagent \
    -r node-polyglot \
    -r async \
    -r moment \
    -r classnames \
    | node_modules/.bin/exorcist client/public/scripts/bundle-vendors.js.map \
    > client/public/scripts/bundle-vendors.js
