#!/bin/bash
cp src/client/index.jade dist/client
REV=$(git rev-parse --short HEAD)

# replace dev value by prod value in template
sed -i '' \
    -e 's/script(src="scripts\/bundle-vendors.js")//g' \
    -e 's/bundle.js/bundle.js?'$REV'/g' \
    -e 's/application.css/application.css?'$REV'/g' dist/client/index.jade

# pre-compile the template
node_modules/.bin/jade dist/client/index.jade --client --no-debug --output

# append node stuff so it can be required by the application
echo "var jade = require('jade/runtime');module.exports=" \
    | cat - dist/client/index.js > dist/client/index.tmp.js
mv dist/client/index.tmp.js dist/client/index.js

# clean compilation remaining
rm dist/client/index.jade
