#!/bin/bash
node_modules/.bin/browserify \
    --debug \
    -t babelify \
    -t [ envify --NODE_ENV production ] \
    --extension='.jsx' \
    --extension='.js' \
    -e client/src/initialize.js \
    > build/client/public/scripts/bundle.js
