#!/bin/bash
node_modules/.bin/stylus \
    -w \
    --include-css \
    --sourcemap \
    --sourcemap-inline \
    --use ./node_modules/nib/lib/nib \
    src/client/app/styles/application.styl \
    -o src/client/public/styles
