#!/bin/bash
node_modules/.bin/watchify -dv \
    -t coffeeify \
    --extension='.coffee' \
    -e client/src/initialize.coffee \
    -o client/public/scripts/bundle.js.tmp  \
    -x jquery \
    -x underscore \
    -x backbone \
    -x react/addons \
    -x superagent \
    -x node-polyglot \
    -x async \
    -x moment
