#!/bin/bash
./node_modules/.bin/watchify -dv \
    -t coffeeify \
    -t babelify \
    --extension=".coffee" \
    --extension=".jsx" \
    --extension=".js" \
    -e client/src/initialize.js \
    -o 'node_modules/.bin/exorcist client/public/scripts/bundle.js.map > client/public/scripts/bundle.js' \
    -x underscore \
    -x react/addons \
    -x superagent \
    -x node-polyglot \
    -x async \
    -x moment \
    -x classnames \
    -x react-router \
    -x flux 
