#!/bin/bash
./node_modules/.bin/watchify -dv \
    -t coffeeify \
    --extension=".coffee" \
    -e client/src/initialize.coffee \
    -o 'node_modules/.bin/exorcist client/public/scripts/bundle.js.map > client/public/scripts/bundle.js' \
    -x jquery \
    -x underscore \
    -x backbone \
    -x react/addons \
    -x superagent \
    -x node-polyglot \
    -x async \
    -x moment \
    -x classnames \
    -x react-router
